import { StoreProvider } from "@/store/storeProvider";
import "./globals.css";
import Head from "next/head";
import NestLinkImg from "@/images/NestLink.png";

export const metadata = {
  title: "NestLinks",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href={NestLinkImg} />
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{metadata.title}</title>
      </Head>
      <body>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
