"use client";
import AppSidebar from "@/components/layout/AppSidebar";
import { faBars, faLink } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { Lato } from "next/font/google";
import "../globals.css";
import Image from "next/image";
import { redirect } from "next/navigation";
import { Toaster } from "react-hot-toast";
import useAuth from "@/hooks/useAuth";
import Link from "next/link";
import { StoreProvider } from "@/store/storeProvider";
import PageSettingsForm from "@/components/forms/PageSettingsForm";

import getUsername from "@/utils/getUsername";
import NestLinkImg from "@/images/NestLink.png";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppTemplate({ children, ...rest }) {
  const { isLoggedIn } = useAuth();
  const { username } = getUsername();

  return (
    <>
      <html lang="en">
        <body className={lato.className}>
          <Toaster />
          <main className="flex min-h-screen">
            <label
              htmlFor="navCb"
              className="md:hidden fixed ml-4 mt-4 p-4 rounded-md bg-white shadow items-center gap-2 cursor-pointer"
            >
              <FontAwesomeIcon icon={faBars} />
              <span></span>
            </label>
            <input id="navCb" type="checkbox" className="hidden" />
            <label
              htmlFor="navCb"
              className="hidden backdrop fixed inset-0 bg-black/80 z-10"
            ></label>
            <aside className="bg-white w-48 p-4 pt-6 shadow fixed md:static -left-48 top-0 bottom-0 z-20 transition-all">
              <div className="sticky top-0 pt-2">
                <div className="rounded-full overflow-hidden aspect-square w-24 mx-auto">
                  <Image
                    src={NestLinkImg}
                    width={170}
                    height={170}
                    alt={"avatar"}
                  />
                </div>
                {username && (
                  <Link
                    target="_blank"
                    href={"/" + username}
                    className="text-center mt-4 flex gap-1 items-center justify-center"
                  >
                    <FontAwesomeIcon
                      size="lg"
                      icon={faLink}
                      className="text-blue-500"
                    />
                    <span className="text-xl text-gray-300">/</span>
                    <span>{username}</span>
                  </Link>
                )}
                <div className="">
                  <AppSidebar />
                </div>
              </div>
            </aside>
            <PageSettingsForm />
          </main>
        </body>
      </html>
    </>
  );
}
